apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
      - name: consumer
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
        image: ochorny/consumer
        env:
          - name: REDIS_HOST
            value: redis-master
          - name: REDIS_PORT
            value: "6379"
          - name: REDIS_ADDRESS
            value: redis-slave.default.svc.cluster.local:6379
        imagePullPolicy: Always
