apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: publish
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:  
  rules:  
    - http:
        paths:                
        - backend:
            serviceName: publisher-service
            servicePort: 8080
          path: /publish(/|$)(.*)
        - backend:
            serviceName: prometheus-service
            servicePort: 9090
          path: /()(.*)

